# Sourced by ifdl and ifset; these are consumed there, not here
# shellcheck shell=sh disable=SC2034
IFUP="/sbin/ifup"
IFDOWN="/sbin/ifdown"

NETWORK="/etc/network"

FILES="$NETWORK/interfaces \
       /etc/hosts \
       /etc/pcmcia/wlan-ng.opts \
       /etc/resolv.conf \
       /etc/ssh/ssh_config \
       /etc/wlan/wlan.conf"
